export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const SPREADSHEET_REPOSITORY = Symbol('SPREADSHEET_REPOSITORY');
export const FILE_STORAGE = Symbol('FILE_STORAGE');
